sudo: required
services: 
  - docker

before_install:
  - docker build -t kiruthiharan/react-test -f ./client/Dockerfile.dev

script:
  - docker run kiruthiharan/react-test npm test -- --coverage

after_success:
  - docker build -t kiruthiharan/multi-client ./client
  - docker build -t kiruthiharan/multi-nginx ./nginx
  - docker build -t kiruthiharan/multi-server ./server
  - docker build -t kiruthiharan/multi-worker ./worker
  # log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take these images and push to docker hub
  - docker push kiruthiharan/multi-client
  - docker push kiruthiharan/multi-nginx
  - docker push kiruthiharan/multi-server
  - docker push kiruthiharan/multi-worker

